name: Transcribe Audio

on:
  push:
    paths:
      - 'audio/**.m4a'
      - 'audio/**.mp3'
      - 'audio/**.wav'
      - '.github/workflows/transcribe.yml'

jobs:
  transcribe:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/openai/whisper.git
        sudo apt-get update && sudo apt-get install ffmpeg -y

    - name: Convert audio and transcribe
      run: |
        mkdir -p transcript
        mkdir -p temp_wav

        # 转换 .m4a, .mp3 为标准 .wav
        for f in audio/*; do
          [ -f "$f" ] || continue
          ext="${f##*.}"
          filename=$(basename "$f")
          name="${filename%.*}"

          if [[ "$ext" == "m4a" || "$ext" == "mp3" ]]; then
            echo "Converting $f to WAV..."
            ffmpeg -i "$f" -ar 16000 -ac 1 -c:a pcm_s16le "temp_wav/$name.wav"
          elif [[ "$ext" == "wav" ]]; then
            cp "$f" "temp_wav/$name.wav"
          else
            echo "Skipping unsupported file: $f"
          fi
        done

        # 识别所有 wav 文件
        for f in temp_wav/*.wav; do
          [ -f "$f" ] || continue
          echo "Transcribing $f..."
          whisper "$f" --language Chinese --output_format txt --output_dir transcript
        done

    - name: Upload transcript as artifact
      uses: actions/upload-artifact@v4
      with:
        name: transcribed-text
        path: transcript/
